version: "3.9"

services:

  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: internship-mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: project_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpass}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20  
    networks:
      - project-net

  user-service:
    build:
      context: ./backend/user
      dockerfile: Dockerfile
    container_name: internship-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://internship-mysql:3306/project_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-dbuser}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-dbpass}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-dummy_cloud}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-dummy_key}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-dummy_secret}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - project-net

  sensor-service:
    build:
      context: ./backend/sensor_data
      dockerfile: Dockerfile
    container_name: internship-sensor
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://internship-mysql:3306/project_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-dbuser}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-dbpass}
      USER_SERVICE_URL: http://user-service:8080
    depends_on:
      mysql:
        condition: service_healthy

      user-service:
        condition: service_started
    networks:
      - project-net

  simulator:
    build:
      context: ./simulator
      dockerfile: Dockerfile
    container_name: internship-simulator
    environment:
      SENSOR_SERVICE_URL: http://sensor-service:8081
      TRAFFIC_INTERVAL_SECONDS: 300
      LIGHT_INTERVAL_SECONDS: 120
      AIR_INTERVAL_SECONDS: 30
    depends_on:
      sensor-service:
        condition: service_started
    networks:
      - project-net

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: internship-frontend
    ports:
      - "4200:80"
    depends_on:
      - user-service
      - sensor-service
    networks:
      - project-net

volumes:
  mysql_data:

networks:
  project-net:
    driver: bridge