apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-service
  labels:
    app: sensor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-service
  template:
    metadata:
      labels:
        app: sensor-service
    spec:
      containers:
        - name: sensor-service
          image: nadinahmed/sensor-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/project_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME_FILE
              value: /run/secrets/mysql_user
            - name: SPRING_DATASOURCE_PASSWORD_FILE
              value: /run/secrets/mysql_password
            - name: USER_SERVICE_URL
              value: "http://user-service:8080"
          volumeMounts:
            - name: mysql-secrets
              mountPath: /run/secrets/mysql_user
              subPath: mysql_user
              readOnly: true
            - name: mysql-secrets
              mountPath: /run/secrets/mysql_password
              subPath: mysql_password
              readOnly: true
      volumes:
        - name: mysql-secrets
          secret:
            secretName: mysql-secret
