spring.application.name=user

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/project_db}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# SpringDoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

jwt.secret=DrQtulRpM8tRDX53cFscl5ClQWOYDXNWQgVIHeVww1s=
jwt.expiration-ms=3600000
